### ISSUE TITLE
.text(string) assertion

### ISSUE THREAD

**Issue by rkotze** [rkotze/should-enzyme#1]
Assert the text is correct in the element selected.

**Comment by RobAWilkinson** [comment]
I can tackle this

**Comment by RobAWilkinson** [comment]
any particular reason you're using this generic `boolAssertionBuilder` function? 
`text()` returns a string and i can do a match on it, but cannot be given an argument which is what your function expects

**Comment by rkotze** [comment]
Hi @RobAWilkinson - I was basically aiming to make one generic function to build all should asserts `boolAssertionBuilder`. But this is not a concrete, probably too complex to achieve. I'm open to the ideas as this library is in its early stages, the pattern still needs to be established.

Also I've add get `text()` function in the `base-enzyme` wrapper.

**Comment by RobAWilkinson** [comment]
Its possible, im hoping a pattern emerges with some other more complicated
enzyme functions.
