### ISSUE TITLE
Present assert

### ISSUE THREAD

**Issue by rkotze** [rkotze/should-enzyme#10]
`present()` assert to check element is there. 

e.g. `mount(<MyComponent />).find('.myElement').should.be.present()`.

**Comment by sashashakun** [comment]
Hello! I want to help with this. 
Will make a PR in a day or two. Is it ok?

**Comment by rkotze** [comment]
Yes that cool. :+1:

**Comment by sashashakun** [comment]
@rkotze I start work on PR for this. Can you please advice what exactly should `present` checks? Thanks.

**Comment by rkotze** [comment]
@sashashakun it should assert the wrapper exists, examples:

`mount(<Fixture />).find('.elementId').should.be.present()` - so there should at one or more elements with this className and this will pass else it should fail.

`mount(<EmptyFixture />).should.be.present()` - should be true as well event though it might empty the wrapper is present.

Does that help?

**Comment by sashashakun** [comment]
@rkotze Yep, thanks! Sorry for the late responce, I am still here, and I am working on this😉

**Comment by rkotze** [comment]
Hi @sashashakun - are you still able to do this? I'm happy to take over if you don't have time :)

**Comment by sashashakun** [comment]
@rkotze unfortunately yes, I dont have time for this:(
I am really sorry.

**Comment by rkotze** [comment]
@sashashakun no worries.
