### ISSUE TITLE
peer deps are out of date.

### ISSUE THREAD

**Issue by createthis** [rkotze/should-enzyme#24]
Peer deps are out of date. We're up to should 13 now.

**Comment by rkotze** [comment]
This is merged in. Thanks for your contributions.

I have fixed the breaking tests when upgrading to should 12 and 13.x in these commits: 1c5baf0c7e49fbc128d21f56bb71d516cba626cc & e2e486826454146b6d97b2dd11f4c25e88c03114.

I've released this changes in should-enzyme v2.10

**Comment by nwhitmont** [comment]
@rkotze Did you mean published in `2.1.0` instead of `2.10.0`? It's listed as current `2.1.0` on npm: https://www.npmjs.com/package/should-enzyme

**Comment by rkotze** [comment]
oops, Yes I mean 2.1.0 👍
