### ISSUE TITLE
.find(elem) assertion

### ISSUE THREAD

**Issue by RobAWilkinson** [rkotze/should-enzyme#7]
Example
I'm not sure on the syntax on this but I use `find` a ton with my enzyme tests

**Comment by rkotze** [comment]
I guess it depends on what you want to do here. Finding an element is kind of similar to `containsMatchingElement` as you want to assert that element exists.

It could also be something like `present`. To check element you're looking for is there. `mount().find('myElement').should.be.present()`.

So I don't think there will be an assert called `find` but rather things that come after calling `find()`.
