### ISSUE TITLE
.state() assertion

### ISSUE THREAD

**Issue by RobAWilkinson** [rkotze/should-enzyme#8]
I also use `.state()` assertions a ton.
Possible syntax `wrapper.should.have.state({})` ?

**Comment by rkotze** [comment]
Something to think about in terms of making the `should-enzyme` api consistent is if you look at `prop()` that takes a key and value params. But maybe what we want to do is make it accept objects as well.

**Comment by RobAWilkinson** [comment]
Yeah, key value is better in my mind, else we have to worry about deep
equality checking.
